//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name listInt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ZipWebApplication.ServiceReference1.AddResponse Add(ZipWebApplication.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.AddResponse> AddAsync(ZipWebApplication.ServiceReference1.AddRequest request);
        
        // CODEGEN: Generating message contract since element name sourcePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompressFolder", ReplyAction="*")]
        ZipWebApplication.ServiceReference1.CompressFolderResponse CompressFolder(ZipWebApplication.ServiceReference1.CompressFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompressFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.CompressFolderResponse> CompressFolderAsync(ZipWebApplication.ServiceReference1.CompressFolderRequest request);
        
        // CODEGEN: Generating message contract since element name zipFilePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractZipFile", ReplyAction="*")]
        ZipWebApplication.ServiceReference1.ExtractZipFileResponse ExtractZipFile(ZipWebApplication.ServiceReference1.ExtractZipFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractZipFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.ExtractZipFileResponse> ExtractZipFileAsync(ZipWebApplication.ServiceReference1.ExtractZipFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ZipWebApplication.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZipWebApplication.ServiceReference1.ArrayOfInt listInt;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(ZipWebApplication.ServiceReference1.ArrayOfInt listInt) {
            this.listInt = listInt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ZipWebApplication.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompressFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompressFolder", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.CompressFolderRequestBody Body;
        
        public CompressFolderRequest() {
        }
        
        public CompressFolderRequest(ZipWebApplication.ServiceReference1.CompressFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompressFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sourcePath;
        
        public CompressFolderRequestBody() {
        }
        
        public CompressFolderRequestBody(string sourcePath) {
            this.sourcePath = sourcePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompressFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CompressFolderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.CompressFolderResponseBody Body;
        
        public CompressFolderResponse() {
        }
        
        public CompressFolderResponse(ZipWebApplication.ServiceReference1.CompressFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CompressFolderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CompressFolderResult;
        
        public CompressFolderResponseBody() {
        }
        
        public CompressFolderResponseBody(string CompressFolderResult) {
            this.CompressFolderResult = CompressFolderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractZipFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractZipFile", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.ExtractZipFileRequestBody Body;
        
        public ExtractZipFileRequest() {
        }
        
        public ExtractZipFileRequest(ZipWebApplication.ServiceReference1.ExtractZipFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtractZipFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zipFilePath;
        
        public ExtractZipFileRequestBody() {
        }
        
        public ExtractZipFileRequestBody(string zipFilePath) {
            this.zipFilePath = zipFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractZipFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractZipFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZipWebApplication.ServiceReference1.ExtractZipFileResponseBody Body;
        
        public ExtractZipFileResponse() {
        }
        
        public ExtractZipFileResponse(ZipWebApplication.ServiceReference1.ExtractZipFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExtractZipFileResponseBody {
        
        public ExtractZipFileResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ZipWebApplication.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ZipWebApplication.ServiceReference1.WebService1Soap>, ZipWebApplication.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZipWebApplication.ServiceReference1.AddResponse ZipWebApplication.ServiceReference1.WebService1Soap.Add(ZipWebApplication.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(ZipWebApplication.ServiceReference1.ArrayOfInt listInt) {
            ZipWebApplication.ServiceReference1.AddRequest inValue = new ZipWebApplication.ServiceReference1.AddRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.AddRequestBody();
            inValue.Body.listInt = listInt;
            ZipWebApplication.ServiceReference1.AddResponse retVal = ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.AddResponse> ZipWebApplication.ServiceReference1.WebService1Soap.AddAsync(ZipWebApplication.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.AddResponse> AddAsync(ZipWebApplication.ServiceReference1.ArrayOfInt listInt) {
            ZipWebApplication.ServiceReference1.AddRequest inValue = new ZipWebApplication.ServiceReference1.AddRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.AddRequestBody();
            inValue.Body.listInt = listInt;
            return ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZipWebApplication.ServiceReference1.CompressFolderResponse ZipWebApplication.ServiceReference1.WebService1Soap.CompressFolder(ZipWebApplication.ServiceReference1.CompressFolderRequest request) {
            return base.Channel.CompressFolder(request);
        }
        
        public string CompressFolder(string sourcePath) {
            ZipWebApplication.ServiceReference1.CompressFolderRequest inValue = new ZipWebApplication.ServiceReference1.CompressFolderRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.CompressFolderRequestBody();
            inValue.Body.sourcePath = sourcePath;
            ZipWebApplication.ServiceReference1.CompressFolderResponse retVal = ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).CompressFolder(inValue);
            return retVal.Body.CompressFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.CompressFolderResponse> ZipWebApplication.ServiceReference1.WebService1Soap.CompressFolderAsync(ZipWebApplication.ServiceReference1.CompressFolderRequest request) {
            return base.Channel.CompressFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.CompressFolderResponse> CompressFolderAsync(string sourcePath) {
            ZipWebApplication.ServiceReference1.CompressFolderRequest inValue = new ZipWebApplication.ServiceReference1.CompressFolderRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.CompressFolderRequestBody();
            inValue.Body.sourcePath = sourcePath;
            return ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).CompressFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZipWebApplication.ServiceReference1.ExtractZipFileResponse ZipWebApplication.ServiceReference1.WebService1Soap.ExtractZipFile(ZipWebApplication.ServiceReference1.ExtractZipFileRequest request) {
            return base.Channel.ExtractZipFile(request);
        }
        
        public void ExtractZipFile(string zipFilePath) {
            ZipWebApplication.ServiceReference1.ExtractZipFileRequest inValue = new ZipWebApplication.ServiceReference1.ExtractZipFileRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.ExtractZipFileRequestBody();
            inValue.Body.zipFilePath = zipFilePath;
            ZipWebApplication.ServiceReference1.ExtractZipFileResponse retVal = ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).ExtractZipFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.ExtractZipFileResponse> ZipWebApplication.ServiceReference1.WebService1Soap.ExtractZipFileAsync(ZipWebApplication.ServiceReference1.ExtractZipFileRequest request) {
            return base.Channel.ExtractZipFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZipWebApplication.ServiceReference1.ExtractZipFileResponse> ExtractZipFileAsync(string zipFilePath) {
            ZipWebApplication.ServiceReference1.ExtractZipFileRequest inValue = new ZipWebApplication.ServiceReference1.ExtractZipFileRequest();
            inValue.Body = new ZipWebApplication.ServiceReference1.ExtractZipFileRequestBody();
            inValue.Body.zipFilePath = zipFilePath;
            return ((ZipWebApplication.ServiceReference1.WebService1Soap)(this)).ExtractZipFileAsync(inValue);
        }
    }
}
