//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Web_WCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDetails", Namespace="http://schemas.datacontract.org/2004/07/WCFCrud")]
    [System.SerializableAttribute()]
    public partial class CustomerDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
        string InsertCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomerDetails", ReplyAction="http://tempuri.org/IService1/InsertCustomerDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerDetails", ReplyAction="http://tempuri.org/IService1/UpdateCustomerDetailsResponse")]
        string UpdateCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomerDetails", ReplyAction="http://tempuri.org/IService1/UpdateCustomerDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
        System.Data.DataSet GetCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomerDetails", ReplyAction="http://tempuri.org/IService1/GetCustomerDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomerDetails", ReplyAction="http://tempuri.org/IService1/DeleteCustomerDetailsResponse")]
        bool DeleteCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomerDetails", ReplyAction="http://tempuri.org/IService1/DeleteCustomerDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CRUD_Web_WCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CRUD_Web_WCF.ServiceReference1.IService1>, CRUD_Web_WCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.InsertCustomerDetails(cDetails);
        }
        
        public System.Threading.Tasks.Task<string> InsertCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.InsertCustomerDetailsAsync(cDetails);
        }
        
        public string UpdateCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.UpdateCustomerDetails(cDetails);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.UpdateCustomerDetailsAsync(cDetails);
        }
        
        public System.Data.DataSet GetCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.GetCustomerDetails(cDetails);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.GetCustomerDetailsAsync(cDetails);
        }
        
        public bool DeleteCustomerDetails(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.DeleteCustomerDetails(cDetails);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerDetailsAsync(CRUD_Web_WCF.ServiceReference1.CustomerDetails cDetails) {
            return base.Channel.DeleteCustomerDetailsAsync(cDetails);
        }
    }
}
